package main

import (
	"log"
	"os"
)

func main() {

	if len(os.Args) != 2 {
		log.Fatalln("Usage: shred <file_path>")
	}

	// Catch panic generated by `Shred` function
	defer func() {
		if r := recover(); r != nil {
			log.Fatal("Failure, exiting.")
		}
	}()

	filepath := os.Args[1]
	Shred(filepath)
}
